# Generated by Django 5.2.14 on 2026-05-11 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='universities.academicyear'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='universities.faculty'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='universities.major'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='universities.semester'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='universities.university'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verification_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='verification_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_update', 'Needs Update'), ('suspended', 'Suspended')], default='incomplete', max_length=32),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['university', 'faculty', 'major', 'academic_year', 'semester'], name='accounts_st_univers_8febea_idx'),
        ),
    ]
