# Generated by Django 5.2.14 on 2026-05-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_academic_year_studentprofile_faculty_and_more'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_year_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_year_full',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='faculty_code_from_student_number',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_serial_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['faculty_code_from_student_number', 'enrollment_year_code'], name='accounts_st_faculty_cf7118_idx'),
        ),
    ]
