# Generated by Django 6.0 on 2026-06-22 09:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_enrollment_year_code_and_more'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccountRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('student_number', models.CharField(db_index=True, max_length=64)),
                ('password_hash', models.CharField(max_length=255)),
                ('uploaded_card', models.FileField(upload_to='student_account_requests/')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved_pending_otp', 'Approved Pending OTP'), ('otp_sent', 'OTP Sent'), ('active', 'Active'), ('rejected', 'Rejected'), ('needs_update', 'Needs Update'), ('expired', 'Expired')], db_index=True, default='pending_review', max_length=32)),
                ('admin_note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('needs_update_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('otp_hash', models.CharField(blank=True, max_length=255)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('otp_last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_account_request', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_account_requests', to='universities.faculty')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_account_requests', to='universities.major')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_account_requests', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_account_requests', to='universities.university')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='accounts_st_status_cae5ca_idx'), models.Index(fields=['email', 'status'], name='accounts_st_email_7856eb_idx'), models.Index(fields=['phone_number', 'status'], name='accounts_st_phone_n_8dbf9b_idx'), models.Index(fields=['university', 'student_number'], name='accounts_st_univers_b0216e_idx')],
            },
        ),
    ]
