# Generated by Django 6.0 on 2026-06-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentaccountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccountrequest',
            name='otp_resend_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
