# Generated by the final production closure: additive token invalidation state.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0004_security_rbac_and_email_otp")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="session_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
