# Generated by Django 5.2.16 on 2026-07-31 16:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=64, unique=True)),
                ('content_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_reacceptance', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=64, unique=True)),
                ('content_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_reacceptance', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('actor_key', models.CharField(max_length=80)),
                ('endpoint', models.CharField(max_length=255)),
                ('key_hash', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='prod_idempotency_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor_key', 'endpoint', 'key_hash'), name='product_idempotency_scope_key_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='requested', max_length=16)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_for', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_deletion_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='prod_delete_status_sched_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceInstallation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('installation_id', models.UUIDField(unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=16)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('build_number', models.PositiveIntegerField(default=0)),
                ('push_token', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('locale', models.CharField(blank=True, max_length=16)),
                ('timezone_name', models.CharField(blank=True, max_length=64)),
                ('device_model', models.CharField(blank=True, max_length=80)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='prod_install_user_revoked_idx'), models.Index(fields=['platform', 'last_seen_at'], name='prod_install_platform_seen_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.SlugField(max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('platform', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS')], max_length=16)),
                ('role', models.CharField(blank=True, max_length=32)),
                ('expose_to_mobile', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_feature_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', 'platform', 'role'],
                'indexes': [models.Index(fields=['key', 'enabled'], name='prod_feature_key_enabled_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'platform', 'role'), name='product_feature_flag_scope_uniq')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('message_ar', models.TextField(blank=True)),
                ('message_en', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_end_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('bypass_staff', models.BooleanField(default=True)),
                ('bypass_healthchecks', models.BooleanField(default=True)),
                ('retry_after_seconds', models.PositiveIntegerField(default=300)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_maintenance_modes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['enabled', 'starts_at', 'ends_at'], name='prod_maintenance_window_idx')],
            },
        ),
        migrations.CreateModel(
            name='MobileAppReleasePolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=16)),
                ('minimum_supported_version', models.CharField(blank=True, max_length=32)),
                ('minimum_supported_build', models.PositiveIntegerField(default=0)),
                ('latest_version', models.CharField(max_length=32)),
                ('latest_build', models.PositiveIntegerField(default=0)),
                ('update_mode', models.CharField(choices=[('none', 'None'), ('recommended', 'Recommended'), ('required', 'Required')], default='none', max_length=16)),
                ('store_url', models.URLField(blank=True)),
                ('message_ar', models.TextField(blank=True)),
                ('message_en', models.TextField(blank=True)),
                ('grace_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('emergency_update_bypass', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_release_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['platform', '-updated_at'],
                'indexes': [models.Index(fields=['platform', 'is_active'], name='prod_release_platform_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('platform',), name='product_one_active_release_per_platform')],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('terms', 'Terms'), ('privacy', 'Privacy')], max_length=16)),
                ('version', models.CharField(max_length=64)),
                ('locale', models.CharField(blank=True, max_length=16)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'kind', 'accepted_at'], name='prod_consent_user_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'version'), name='product_consent_user_kind_version_uniq')],
            },
        ),
    ]
