# Generated by Django 5.2.14 on 2026-05-11 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='files/')),
                ('file_type', models.CharField(blank=True, max_length=32)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('students_only', 'Students Only'), ('verified_students_only', 'Verified Students Only'), ('major_only', 'Major Only'), ('group_only', 'Group Only'), ('admin_only', 'Admin Only')], default='public', max_length=32)),
                ('is_printable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='universities.academicyear')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='universities.faculty')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='groups.group')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='universities.major')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='universities.semester')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='universities.subject')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='universities.university')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visibility', 'is_active'], name='files_filer_visibil_b8db4f_idx'), models.Index(fields=['university', 'faculty', 'major', 'academic_year', 'semester'], name='files_filer_univers_f2ee90_idx'), models.Index(fields=['group', 'visibility'], name='files_filer_group_i_c4df8f_idx')],
            },
        ),
    ]
