# Generated by Django 5.2.14 on 2026-05-12 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('user_registered', 'User Registered'), ('student_profile_updated', 'Student Profile Updated'), ('verification_submitted', 'Verification Submitted'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('verification_needs_update', 'Verification Needs Update'), ('group_created', 'Group Created'), ('group_updated', 'Group Updated'), ('group_deleted', 'Group Deleted'), ('group_membership_approved', 'Group Membership Approved'), ('group_membership_rejected', 'Group Membership Rejected'), ('group_membership_blocked', 'Group Membership Blocked'), ('file_uploaded', 'File Uploaded'), ('file_updated', 'File Updated'), ('file_deleted', 'File Deleted'), ('announcement_created', 'Announcement Created'), ('announcement_updated', 'Announcement Updated'), ('announcement_deleted', 'Announcement Deleted'), ('print_order_created', 'Print Order Created'), ('print_order_status_changed', 'Print Order Status Changed'), ('support_ticket_created', 'Support Ticket Created'), ('support_ticket_status_changed', 'Support Ticket Status Changed'), ('message_deleted', 'Message Deleted')], max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx')],
            },
        ),
    ]
