# Generated by Django 5.2.14 on 2026-07-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'User Registered'), ('user_role_changed', 'User Role Changed'), ('user_status_changed', 'User Status Changed'), ('user_permission_override_changed', 'User Permission Override Changed'), ('student_profile_updated', 'Student Profile Updated'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('verification_submitted', 'Verification Submitted'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('verification_needs_update', 'Verification Needs Update'), ('verification_card_accessed', 'Verification Card Accessed'), ('group_created', 'Group Created'), ('group_updated', 'Group Updated'), ('group_deleted', 'Group Deleted'), ('group_membership_approved', 'Group Membership Approved'), ('group_membership_rejected', 'Group Membership Rejected'), ('group_membership_blocked', 'Group Membership Blocked'), ('group_external_channel_updated', 'External Channel Updated'), ('group_external_channel_ticket_issued', 'External Channel Ticket Issued'), ('group_external_channel_opened', 'External Channel Opened'), ('file_uploaded', 'File Uploaded'), ('file_updated', 'File Updated'), ('file_deleted', 'File Deleted'), ('file_access_ticket_issued', 'File Access Ticket Issued'), ('announcement_created', 'Announcement Created'), ('announcement_updated', 'Announcement Updated'), ('announcement_deleted', 'Announcement Deleted'), ('print_order_created', 'Print Order Created'), ('print_order_status_changed', 'Print Order Status Changed'), ('print_order_assigned', 'Print Order Assigned'), ('print_order_note_updated', 'Print Order Note Updated'), ('print_pricing_changed', 'Print Pricing Changed'), ('support_ticket_created', 'Support Ticket Created'), ('support_ticket_status_changed', 'Support Ticket Status Changed'), ('support_ticket_assigned', 'Support Ticket Assigned'), ('support_ticket_priority_changed', 'Support Ticket Priority Changed'), ('message_deleted', 'Message Deleted'), ('feedback_submitted', 'Feedback Submitted'), ('feedback_workflow_updated', 'Feedback Workflow Updated'), ('feedback_privacy_requested', 'Feedback Privacy Requested')], max_length=64),
        ),
    ]
