# Generated by Django 6.0 on 2026-06-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'User Registered'), ('user_login_succeeded', 'User Login Succeeded'), ('user_login_failed', 'User Login Failed'), ('user_logged_out', 'User Logged Out'), ('password_changed', 'Password Changed'), ('password_reset_confirmed', 'Password Reset Confirmed'), ('otp_verification_failed', 'OTP Verification Failed'), ('student_profile_updated', 'Student Profile Updated'), ('verification_submitted', 'Verification Submitted'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('verification_needs_update', 'Verification Needs Update'), ('verification_card_preview_token_created', 'Verification Card Preview Token Created'), ('group_created', 'Group Created'), ('group_updated', 'Group Updated'), ('group_deleted', 'Group Deleted'), ('group_membership_approved', 'Group Membership Approved'), ('group_membership_rejected', 'Group Membership Rejected'), ('group_membership_blocked', 'Group Membership Blocked'), ('group_membership_role_changed', 'Group Membership Role Changed'), ('file_uploaded', 'File Uploaded'), ('file_updated', 'File Updated'), ('file_deleted', 'File Deleted'), ('file_accessed', 'File Accessed'), ('file_preview_token_created', 'File Preview Token Created'), ('file_download_token_created', 'File Download Token Created'), ('announcement_created', 'Announcement Created'), ('announcement_updated', 'Announcement Updated'), ('announcement_deleted', 'Announcement Deleted'), ('print_order_created', 'Print Order Created'), ('print_order_assigned', 'Print Order Assigned'), ('print_order_status_changed', 'Print Order Status Changed'), ('print_order_note_updated', 'Print Order Note Updated'), ('print_file_preview_token_created', 'Print File Preview Token Created'), ('support_ticket_created', 'Support Ticket Created'), ('support_ticket_assigned', 'Support Ticket Assigned'), ('support_ticket_status_changed', 'Support Ticket Status Changed'), ('support_ticket_priority_changed', 'Support Ticket Priority Changed'), ('support_ticket_staff_reply', 'Support Ticket Staff Reply'), ('message_deleted', 'Message Deleted'), ('message_reported', 'Message Reported'), ('student_account_request_submitted', 'Student Account Request Submitted'), ('student_account_request_approved', 'Student Account Request Approved'), ('student_account_request_rejected', 'Student Account Request Rejected'), ('student_account_request_needs_update', 'Student Account Request Needs Update'), ('student_account_otp_generated', 'Student Account OTP Generated'), ('student_account_otp_resent', 'Student Account OTP Resent'), ('student_account_otp_verified', 'Student Account OTP Verified'), ('student_account_otp_failed', 'Student Account OTP Failed'), ('student_account_activated', 'Student Account Activated'), ('student_account_card_preview_token_created', 'Student Account Card Preview Token Created')], max_length=64),
        ),
    ]
