# Generated by Django 5.2.14 on 2026-05-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['university__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='universitie_is_acti_73fb5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='universities.faculty')),
            ],
            options={
                'ordering': ['faculty__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='universitie_is_acti_211a9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='universities.academicyear')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='universities.major')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='universities.semester')),
            ],
            options={
                'ordering': ['major__name', 'academic_year__order', 'semester__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='universitie_is_acti_d3dcd7_idx'), models.Index(fields=['code'], name='universitie_code_4bbf30_idx')],
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='universities.university'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['faculty', 'is_active'], name='universitie_faculty_6f80fb_idx'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['code'], name='universitie_code_a92c0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='major',
            constraint=models.UniqueConstraint(fields=('faculty', 'name'), name='unique_major_name_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='major',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('faculty', 'code'), name='unique_major_code_per_faculty'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['major', 'academic_year', 'semester', 'is_active'], name='universitie_major_i_acf51f_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='universitie_code_994321_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('major', 'academic_year', 'semester', 'name'), name='unique_subject_name_per_major_year_semester'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('major', 'code'), name='unique_subject_code_per_major'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['university', 'is_active'], name='universitie_univers_9d8e65_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['code'], name='universitie_code_21cc47_idx'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='unique_faculty_name_per_university'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('university', 'code'), name='unique_faculty_code_per_university'),
        ),
    ]
