# Generated by Django 5.2.14 on 2026-05-11 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_studentprofile_academic_year_studentprofile_faculty_and_more'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('student_number', models.CharField(max_length=64)),
                ('card_image', models.ImageField(upload_to='verification_cards/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_update', 'Needs Update'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='universities.academicyear')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='universities.faculty')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='universities.major')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verification_requests', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='universities.semester')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='accounts.studentprofile')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='verificatio_status_ce4069_idx'), models.Index(fields=['university', 'faculty', 'major', 'academic_year'], name='verificatio_univers_8167db_idx'), models.Index(fields=['student_number'], name='verificatio_student_41ca2c_idx')],
            },
        ),
    ]
