# Generated by Django 5.2.16 on 2026-07-31 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_file', models.FileField(upload_to='lectures/originals/')),
                ('original_filename', models.CharField(max_length=255)),
                ('original_mime_type', models.CharField(max_length=128)),
                ('original_size', models.PositiveBigIntegerField()),
                ('original_sha256', models.CharField(db_index=True, max_length=64)),
                ('viewer_pdf', models.FileField(blank=True, upload_to='lectures/viewer/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('scanning', 'Scanning'), ('converting', 'Converting'), ('extracting', 'Extracting'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('failed', 'Failed'), ('quarantined', 'Quarantined')], default='uploaded', max_length=16)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('processing_task_id', models.CharField(blank=True, max_length=255)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lectures', to='universities.subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_lectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('selected_text', models.TextField(blank=True)),
                ('anchor_data', models.JSONField(blank=True, default=dict)),
                ('content', models.TextField()),
                ('color', models.CharField(blank=True, max_length=32)),
                ('note_type', models.CharField(default='note', max_length=32)),
                ('is_bookmark', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('idempotency_key_hash', models.CharField(blank=True, max_length=64)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lectures.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LecturePage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('page_number', models.PositiveIntegerField()),
                ('rendered_file', models.FileField(upload_to='lectures/pages/')),
                ('thumbnail', models.FileField(blank=True, upload_to='lectures/thumbnails/')),
                ('text_content', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='lectures.lecture')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='LectureViewerSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('max_page_requests', models.PositiveIntegerField()),
                ('page_request_count', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_sessions', to='lectures.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_viewer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LectureViewEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='lectures.lecture')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lectures.lectureviewersession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_view_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['subject', 'status', 'is_published'], name='lectures_subject_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['is_published', 'created_at'], name='lectures_published_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(condition=models.Q(('original_sha256', ''), _negated=True), fields=('subject', 'original_sha256'), name='lectures_subject_original_hash_uniq'),
        ),
        migrations.AddIndex(
            model_name='lecturenote',
            index=models.Index(fields=['student', 'lecture', 'page_number'], name='lectures_note_student_page_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturenote',
            index=models.Index(fields=['lecture', 'updated_at'], name='lectures_note_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='lecturenote',
            constraint=models.CheckConstraint(condition=models.Q(('page_number__isnull', True), ('page_number__gte', 1), _connector='OR'), name='lectures_note_valid_page_number'),
        ),
        migrations.AddConstraint(
            model_name='lecturenote',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key_hash', ''), _negated=True), fields=('student', 'lecture', 'idempotency_key_hash'), name='lectures_note_idempotency_uniq'),
        ),
        migrations.AddIndex(
            model_name='lecturepage',
            index=models.Index(fields=['lecture', 'page_number'], name='lectures_page_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='lecturepage',
            constraint=models.UniqueConstraint(fields=('lecture', 'page_number'), name='lectures_page_unique'),
        ),
        migrations.AddIndex(
            model_name='lectureviewersession',
            index=models.Index(fields=['token', 'expires_at'], name='lectures_session_token_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureviewevent',
            index=models.Index(fields=['lecture', 'created_at'], name='lectures_view_event_idx'),
        ),
    ]
