# Generated by Django 5.2.14 on 2026-05-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='send_messages_permission',
            field=models.CharField(choices=[('all_members', 'All Members'), ('admins_only', 'Admins Only')], default='all_members', max_length=32),
        ),
    ]
