from decouple import Csv, config

from .base import *  # noqa: F403

DEBUG = False
RETURN_DEVELOPMENT_OTP = False
ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_SSL_REDIRECT = config_bool("SECURE_SSL_REDIRECT", default=True)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_SECONDS = 31536000
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = config_bool("SESSION_COOKIE_SECURE", default=True)
CSRF_COOKIE_SECURE = config_bool("CSRF_COOKIE_SECURE", default=True)
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())
