# Generated by Django 5.2.14 on 2026-05-12 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('printing', 'Printing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='submitted', max_length=32)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('student_priority', 'Student Priority'), ('urgent', 'Urgent')], default='normal', max_length=32)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_print_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintOrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='print_orders/')),
                ('original_file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=32)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('pages_count', models.PositiveIntegerField(blank=True, null=True)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('color_mode', models.CharField(choices=[('black_white', 'Black and White'), ('color', 'Color')], default='black_white', max_length=32)),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('A3', 'A3')], default='A4', max_length=8)),
                ('sides', models.CharField(choices=[('one_sided', 'One Sided'), ('double_sided', 'Double Sided')], default='one_sided', max_length=32)),
                ('binding', models.CharField(choices=[('none', 'None'), ('staple', 'Staple'), ('spiral', 'Spiral'), ('thermal', 'Thermal')], default='none', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='printing.printorder')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_order_items', to='files.fileresource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('printing', 'Printing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], max_length=32)),
                ('new_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('printing', 'Printing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='printing.printorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='printorder',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='printing_pr_status_1cd497_idx'),
        ),
        migrations.AddIndex(
            model_name='printorder',
            index=models.Index(fields=['user', 'status'], name='printing_pr_user_id_7d56ae_idx'),
        ),
        migrations.AddIndex(
            model_name='printorder',
            index=models.Index(fields=['assigned_to', 'status'], name='printing_pr_assigne_85eab5_idx'),
        ),
        migrations.AddIndex(
            model_name='printorderstatushistory',
            index=models.Index(fields=['order', 'created_at'], name='printing_pr_order_i_fc69ac_idx'),
        ),
    ]
