# Generated by Django 5.2.14 on 2026-07-29 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_split_public_internal_status_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='idempotency_key_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='printorder',
            name='pricing_revision',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='printorder',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key_hash', ''), _negated=True), fields=('user', 'idempotency_key_hash'), name='unique_print_order_idempotency_key'),
        ),
    ]
