# Generated by Django 5.2.14 on 2026-07-29 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_extended_feedback_contexts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAITriage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('human_corrected', 'Human Corrected')], default='queued', max_length=24)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('topic', models.CharField(blank=True, max_length=128)),
                ('sentiment', models.CharField(blank=True, max_length=32)),
                ('suggested_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('redacted_text', models.TextField(blank=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='abuse_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='content_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='experiment_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='journey_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='metric_type',
            field=models.CharField(choices=[('csat', 'Customer Satisfaction'), ('ces', 'Customer Effort Score'), ('nps', 'Net Promoter Score'), ('stars', 'Stars'), ('free_text', 'Free Text')], default='stars', max_length=16),
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='metric_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='release_channel',
            field=models.CharField(blank=True, choices=[('production', 'Production'), ('beta', 'Beta'), ('internal', 'Internal')], max_length=16),
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='source_screen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feedbackpromptpolicy',
            name='dismiss_cooldown_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='feedbackpromptpolicy',
            name='locales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feedbackpromptpolicy',
            name='max_prompts_per_30_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedbackpromptpolicy',
            name='maximum_app_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='feedbackpromptpolicy',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feedbackpromptpolicy',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feedbackpromptpolicy',
            name='verification_statuses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='appfeedback',
            index=models.Index(fields=['metric_type', 'metric_value', 'created_at'], name='feedback_metric_created_idx'),
        ),
        migrations.AddIndex(
            model_name='appfeedback',
            index=models.Index(fields=['platform', 'app_version', 'created_at'], name='feedback_version_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='appfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('metric_value__isnull', True), models.Q(('metric_type__in', ['csat', 'stars']), ('metric_value__gte', 1), ('metric_value__lte', 5)), models.Q(('metric_type', 'ces'), ('metric_value__gte', 1), ('metric_value__lte', 7)), models.Q(('metric_type', 'nps'), ('metric_value__gte', 0), ('metric_value__lte', 10)), _connector='OR'), name='feedback_metric_value_in_range'),
        ),
        migrations.AddField(
            model_name='feedbackaitriage',
            name='feedback',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_triage', to='feedback.appfeedback'),
        ),
        migrations.AddField(
            model_name='feedbackaitriage',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback_triages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackaitriage',
            name='similar_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarity_references', to='feedback.appfeedback'),
        ),
        migrations.AddIndex(
            model_name='feedbackaitriage',
            index=models.Index(fields=['status', 'created_at'], name='feedback_ai_status_created_idx'),
        ),
    ]
